### ISSUE TITLE
Example code casadi.nlpsol NotImplementedError

### ISSUE THREAD

**Issue by JeroenDM** [casadi/python-optistack#1]
Using spyder, python 2.7.6 and numpy 1.8.2 on Ubuntu 14.04 LTS.
I tried to run the example code:

````
from sys import path

path.append(r"/home/jeroen/casadi-py27-np1.9.1-v3.1.0-rc1")
path.append(r"/home/jeroen/python-optistack-master")

from optistack import *
x = optivar()
y = optivar()

nlp = optisolve((1-x)**2 + 100*(y-x**2)**2, [x**2 + y**2 <= 1, x + y >= 0])

print optival(x)
print optival(y)
````

And I got the following NotImplementedError:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

In [1]: runfile('/home/jeroen/Documents/python/num_opt/test_casadi_save.py', wdir='/home/jeroen/Documents/python/num_opt')
Traceback (most recent call last):

  File "<ipython-input-1-5de8d14b4028>", line 1, in <module>
    runfile('/home/jeroen/Documents/python/num_opt/test_casadi_save.py', wdir='/home/jeroen/Documents/python/num_opt')

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "/home/jeroen/Documents/python/num_opt/test_casadi_save.py", line 17, in <module>
    nlp = optisolve((1-x)**2 + 100*(y-x**2)**2, [x**2 + y**2 <= 1, x + y >= 0])

  File "/home/jeroen/python-optistack-master/optistack/optisolve.py", line 85, in __init__
    self.solver = C.nlpsol('solver','ipopt', nlp, options)

  File "/home/jeroen/casadi-py27-np1.9.1-v3.1.0-rc1/casadi/casadi.py", line 15056, in nlpsol
    return _casadi.nlpsol(*args)

NotImplementedError: Wrong number or type of arguments for overloaded function 'nlpsol'.
  Possible prototypes are:
    nlpsol(str,str,Importer,dict)
    nlpsol(str,str,dict:SX,dict)
    nlpsol(str,str,dict:MX,dict)
    nlpsol(str,str,str,dict)
  You have: '(str,str,Function,dict)'
```
Am I doing something wrong?

I looked at the code of optisolve and it looks as if a casadi.Function is passed as a third argument at line 83 to 85:

```
nlp = C.Function('nlp', {"x":X,"p":P,"f":objective,"g":gl_pure_v},["x","p"],["f","g"],opt)
self.solver = C.nlpsol('solver','ipopt', nlp, options)
```

**Comment by jgillis** [comment]
Good call; basically python-optistack is only compatible with CasADi 3.0.0, not 3.1.0-rc1 at this point..

**Comment by JeroenDM** [comment]
Ok, thank you! I downloaded CasADi 3.0.0 and it's working now.

**Comment by jgillis** [comment]
Fwiw, now works with 3.1
