### ISSUE TITLE
Strange error message when using optival() on wrong variable

### ISSUE THREAD

**Issue by JeroenDM** [casadi/python-optistack#2]
Maybe not a priority, but I get a confusing error message when I used optival() where I should have used optivar(). The following code

> from optistack import *
> n = 10
> x = optival(n)

results in the error message `NameError: global name 'MX' is not defined`.

The complete output was:

> runfile('/home/jeroen/Desktop/test_optistack.py', wdir='/home/jeroen/Desktop')
> Traceback (most recent call last):
> 
>   File "<ipython-input-2-e12d59d809a4>", line 1, in <module>
>     runfile('/home/jeroen/Desktop/test_optistack.py', wdir='/home/jeroen/Desktop')
> 
>   File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
>     execfile(filename, namespace)
> 
>   File "/home/jeroen/Desktop/test_optistack.py", line 16, in <module>
>     x = optival(n)
> 
>   File "/home/jeroen/python-optistack-master/optistack/optival.py", line 20, in optival
>     symbols = [MX.sym("dummy")]
> 
> NameError: global name 'MX' is not defined
>

**Comment by jgillis** [comment]
can you check again?

**Comment by JeroenDM** [comment]
Now the error message is:

> Traceback (most recent call last):
> 
>   File "<ipython-input-1-d6f7249c36cd>", line 1, in <module>
>     runfile('/home/jeroen/Documents/gitlab/path_planning_manipulator/test_python_optistack/test_optistack.py', wdir='/home/jeroen/Documents/gitlab/path_planning_manipulator/test_python_optistack')
> 
>   File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 540, in runfile
>     execfile(filename, namespace)
> 
>   File "/home/jeroen/Documents/gitlab/path_planning_manipulator/test_python_optistack/test_optistack.py", line 16, in <module>
>     x = optival(n)
> 
>   File "/home/jeroen/Documents/github/python-optistack/optistack/optival.py", line 29, in optival
>     out = f.call(f_inputs)
> 
>   File "/home/jeroen/casadi-py27-np1.9-v3.2.0/casadi/casadi.py", line 11419, in call
>     return _casadi.Function_call(self, *args)
> 
> RuntimeError: The assertion "arg.size()==n_in" on line 935 of file "/home/travis/build/casadi/binaries/casadi/casadi/core/function_internal.hpp" failed. 
> Incorrect number of inputs: Expected 1, got 0
